services:
  sync-alicdn-cert:
    container_name: sync-alicdn-cert
    image: sync-alicdn-cert
    environment:
      - ACCESS_KEY_ID=xxx
      - ACCESS_KEY_SECRET=xxx
      - DOMAIN=xxx
      - LETS_ENCRYPT_CERTS_PATH=/cert
    volumes:
      - /data/ssl/xxx:/cert:ro