version: '3.7'

services:
  sync-alicdn-cert:
    container_name: sync-alicdn-cert
    image: sync-alicdn-cert
    environment:
      - ACCESS_KEY_ID=xxx
      - ACCESS_KEY_SECRET=xxx
      - DOMAIN=i.bstu.cn
      - LETS_ENCRYPT_CERTS_PATH=/cert
    volumes:
      - /root/.acme.sh/bstu.cn:/cert:ro
