name: deploy

on:
  push:
    branches:
      - nginxproxymanager-sync-alicdn-cert
  schedule:
    - cron: '20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v3 # git pull

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Packages
        run: yarn

      - name: Build
        run: yarn build

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/sliwei/nginxproxymanager-sync-alicdn-cert:1.0.0
          # 推送镜像到镜像仓库
          docker push registry.cn-shenzhen.aliyuncs.com/sliwei/nginxproxymanager-sync-alicdn-cert:1.0.0

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /data/docker/nginxproxymanager-sync-alicdn-cert
            # 登录阿里云镜像仓库
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
            docker pull registry.cn-shenzhen.aliyuncs.com/sliwei/nginxproxymanager-sync-alicdn-cert:1.0.0
            docker compose up -d

